<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CEI.ReportGenerator.SmokeTests</RootNamespace>
    <AssemblyName>CEI.ReportGenerator.SmokeTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CEI.ReportGenerator.App\CEI.ReportGenerator.App.csproj" />
    <ProjectReference Include="..\CEI.ReportGenerator.Core\CEI.ReportGenerator.Core.csproj" />
    <ProjectReference Include="..\CEI.ReportImporter.Core\CEI.ReportImporter.Core.csproj" />
  </ItemGroup>

</Project>
